class Memory:

    def __init__(self):
        self.embeddings = []
        self.embeddings_1 = []
        self.embeddings_2 = []
        self.edge_index = []
        self.edge_index_n = []
        self.edge_index_1 = []
        self.edge_index_2 = []
        self.edge_attr_1 = []
        self.edge_attr_2 = []
        self.state = []
        self.input = []
        self.actions = []
        self.action_log_probs = []
        self.rewards = []
        self.is_terminals = []

    def clear_memory(self):
        del self.embeddings[:]
        del self.embeddings_1[:]
        del self.embeddings_2[:]
        del self.edge_index[:]
        del self.edge_index_n[:]
        del self.edge_index_1[:]
        del self.edge_index_2[:]
        del self.edge_attr_1[:]
        del self.edge_attr_2[:]
        del self.state[:]
        del self.input[:]
        del self.actions[:]
        del self.action_log_probs[:]
        del self.rewards[:]
        del self.is_terminals[:]
